### PR TITLE
added precision on workspace.xml

### PR DESCRIPTION
**Pull request by simonelbaz**

### CODE REVIEW

**Comment by tanandy** [comment]
Hi @simonelbaz @fmartin-linagora  can we backport / close this PR?

**Comment by fmartin-linagora** [comment]
I think Simon already did the work on our gitlab, so this MR is useless now. Simon, can you confirm  ?

**Comment by simonelbaz** [comment]
yes, i did

**Comment by fmartin-linagora** [comment]
Ok, I'm closing it. tks.

**Pull request closed without merging**
